### ISSUE TITLE
Paygol

### ISSUE THREAD

**Issue by ondrejvajdak** [RedDuckss/PHP-Vanilla-Buycraft#1]
Is here any way, to pay with Paygol and PayPal?

**Comment by jonbarrow** [comment]
This is just an open source example, not something to be used as-is. It says so in the readme section of the repo. If you want to add support for multiple payment gateways, you'll have to add it yourself

**Comment by jonbarrow** [comment]
Due to the lack of response, I'll assume this question has been answered and will now close this issue report.
