### ISSUE TITLE
Slim Application Error, Looks different.

### ISSUE THREAD

**Issue by MrLava13** [RedDuckss/PHP-Vanilla-Buycraft#4]
I can't really do coding but I got this, I followed the instructions...

_______________________________________________________________________________________________________________

![error](https://user-images.githubusercontent.com/24940520/46923627-bec06c00-cfd7-11e8-9da1-af46ccb800a8.PNG)

**Comment by MrLava13** [comment]
![error](https://user-images.githubusercontent.com/24940520/46923627-bec06c00-cfd7-11e8-9da1-af46ccb800a8.PNG)

**Comment by MrLava13** [comment]
Found the problem but... it looks like...
![capture](https://user-images.githubusercontent.com/24940520/47258456-9a8de080-d458-11e8-8720-56bae6c0651d.PNG)

**Comment by GeorgeV220** [comment]
you found any solution ?

**Comment by MrLava13** [comment]
An old issue on a stale repository. 

There is no need for this to remain open.
